[package]
name = "mecha-edge-bluetooth-scan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.70"
log = "0.4.19"
bitflags = "1.3.2"
thiserror = "1.0.41"
uuid = "1.4.0"
serde_cr = { package = "serde", version = "1.0.166", features = ["derive"], default-features = false, optional = true }
serde_bytes = { version = "0.11.10", optional = true }
dashmap = "5.4.0"
futures = "0.3.28"
static_assertions = "1.1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
btleplug = "0.11.0"
pretty_env_logger = "0.5.0"

[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.9.7"
bluez-async = "0.7.2"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.19.0"
once_cell = "1.18.0"
jni-utils = "0.1.1"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
cocoa = "0.25.0"
objc = "0.2.7"
libc = "0.2.147"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.48.0", features = ["Devices_Bluetooth", "Devices_Bluetooth_GenericAttributeProfile", "Devices_Bluetooth_Advertisement", "Devices_Radios", "Foundation_Collections", "Foundation", "Storage_Streams"] }

[dev-dependencies]
rand = "0.8.5"
pretty_env_logger = "0.5.0"
tokio = { version = "1.29.1", features = ["macros", "rt", "rt-multi-thread"] }
serde_json = "1.0.100"
